workflow:
  max_iterations: 3
  validation_threshold: 0.8

roles:
  requirement_analyzer:
    temperature: 0.3
  
  task_classifier:
    temperature: 0.5
    
  jd_optimizer:
    temperature: 0.7
    
  jd_validator:
    temperature: 0.2
